SPOTIFY_CLIENT_ID = "dd1a6b68e0ec4ee2abf518a7ee6d7137"
SPOTIFY_CLIENT_SECRET = "0e327146c66843feb056a9e3094efc58"
REDIRECT_URI = "https://cerryrecommends.com/*"
SCOPES = "user-read-private playlist-read-private playlist-modify-private playlist-modify-public user-library-read"